#!/bin/bash

ALL_ARGS=$@

help_message() {
  cat <<EOF

  Usage: gweb [-v] [-h] [branch]

   Help: Open the current git repository on Github or Bitbucket 
         in your default browser. (using 'origin' remote)

Options:
      -v            run verbosely
      -h            print this message

EOF
}

debug_message() {
  if [ "$DEBUG" != "" ]; then
    cat <<EOF
         Args: $ALL_ARGS
 Given Branch: $GIVEN_BRANCH
Branch Handle: $BRANCH_PATH

       Remote: $REMOTE
         Host: $HOST
       Branch: $CURRENT_BRANCH

          URL: $URL
EOF
  fi
}

verbose=0

while getopts hv opt; do
  case "$opt" in
  h)
    help_message
    exit 0
    ;;
  v)
    verbose=1
    shift
    ;;
  \?)
    help_message
    exit 0
    ;;
  esac
done



REMOTE=`git remote -v | awk '/origin.*(fetch)/ {print  $2}'`

HOST=`echo $REMOTE | sed 's/^git@//' | sed 's/\..*//'`

CURRENT_BRANCH=`git branch -l | grep \* | sed 's/\* //'`



# grab last variable
for last; do true; done
GIVEN_BRANCH=$last

if [ "$GIVEN_BRANCH" == "." ]; then
  GIVEN_BRANCH=$CURRENT_BRANCH
fi

if [ "$GIVEN_BRANCH" ]; then
  if [ $HOST == "github" ]; then
    BRANCH_PATH="/tree/$GIVEN_BRANCH"
  elif [ $HOST == "bitbucket" ]; then
    BRANCH_PATH="/branch/$GIVEN_BRANCH"
  fi
fi



URL="`echo $REMOTE | sed 's/:/\//' | sed 's/^git@/https:\/\//' | sed 's/.git$//' | sed 's/^https\/\/\//https:\/\//'`$BRANCH_PATH"

if [ $REMOTE ]; then
  if [ $verbose -ge 1 ]; then
    echo -e "\n  Opening $URL"
  fi

  debug_message

  if [ "$DRY_RUN" != true ]; then
    open $URL
  fi
fi
