#!/bin/bash

verbose=0

while getopts hv opt; do
  case "$opt" in
  h)
    echo ""
    echo "  Opens this repo in your default web browser (using 'origin' remote)"
    echo ""
    echo "  -v    run verbosely"
    echo "  -h    print this message"
    exit 0
    ;;
  v) verbose=1
    ;;
  esac
done

REPO=`git remote -v | awk '/origin.*(fetch)/ {print  $2}' | sed 's/:/\//' | sed 's/^git@/https:\/\//' | sed 's/.git$//' | sed 's/^https\/\/\//https:\/\//'`

if [ $REPO ]; then
  if [ $verbose -ge 1 ]; then
    echo "opening $REPO"
  fi
  open $REPO
fi
