#!/bin/bash

verbose=0

help_message="
  Usage: gweb [-v] [-h]

   Help: Open the current git repository on Github or Bitbucket in your default browser. (using 'origin' remote)

Options:
      -v            run verbosely
      -h, --help    print this message
"

while getopts hv"-help" opt; do
  case "$opt" in
  h)
    echo -e "$help_message"; exit 0
    ;;
  v) verbose=1
    ;;
  esac
done

REPO=`git remote -v | awk '/origin.*(fetch)/ {print  $2}' | sed 's/:/\//' | sed 's/^git@/https:\/\//' | sed 's/.git$//' | sed 's/^https\/\/\//https:\/\//'`

if [ $REPO ]; then
  if [ $verbose -ge 1 ]; then
    echo -e "\nOpening $REPO"
  fi
  open $REPO
fi
